[project]
name = "brand-reputation-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=2.2.1",
    "brightdata-sdk>=1.1.3",
    "memorisdk>=2.3.0",
    "openai>=2.6.1",
    "streamlit>=1.50.0",
]
